"""Day 2: 30 Days of python programming"""
first_name= input ("Write your name:")
last_name= input ("Write your last name:")
full_name= input ("Write your full name:")
country= input ("Write your country:")
city= input ("Write your city:")
age= input ("Write your age:")
year= input ("Write the year you were born:")
is_married= input ("Are you married? (yes/no):")
is_true= input ("Are you true? (yes/no):")
is_light_on= input ("Is the light on? (yes/no):")
# Show the information collected
print("Your full name is:", full_name)
print("Your first name is:", first_name)
print("Your last name is:", last_name)
print("Your country is:", country)
print("Your city is:", city)    
print("Your age is:", age)
print("You were born in the year:", year)
print("Are you married?", is_married)
print("Are you true?", is_true)
print("Is the light on?", is_light_on)
# Level 2 Number 1
type_of_first_name = type(first_name)
type_of_last_name = type(last_name)
type_of_full_name = type(full_name)
type_of_country = type(country)
type_of_city = type(city)
type_of_age = type(age)
type_of_year = type(year)
type_of_is_married = type(is_married)
type_of_is_true = type(is_true)
type_of_is_light_on = type(is_light_on)
"""Show the types of the variables"""
print("Type of first name:", type_of_first_name)
print("Type of last name:", type_of_last_name)
print("Type of full name:", type_of_full_name)
print("Type of country:", type_of_country)
print("Type of city:", type_of_city)
print("Type of age:", type_of_age)
print("Type of year:", type_of_year)
print("Type of is married:", type_of_is_married)
print("Type of is true:", type_of_is_true)
print("Type of is light on:", type_of_is_light_on)
# Level 2 Number 2
len_first_name= len(first_name)
print("Lenght of first name is:", len_first_name)
# Level 2 Number 3  
len_last_name= len(last_name)
print("Lenght of last name is:", len_last_name)
print("Lenght of your first name is:" ,len_first_name and "Lenght of your last name is:", len_last_name)