"""Day 2: 30 Days of python programming"""
first_name= input ("Write your name:")
last_name= input ("Write your last name:")
full_name= input ("Write your full name:")
country= input ("Write your country:")
city= input ("Write your city:")
age= input ("Write your age:")
year= input ("Write the year you were born:")
is_married= input ("Are you married? (yes/no):")
is_true= input ("Are you true? (yes/no):")
is_light_on= input ("Is the light on? (yes/no):")
# Show the information collected
print("Your full name is:", full_name)
print("Your first name is:", first_name)
print("Your last name is:", last_name)
print("Your country is:", country)
print("Your city is:", city)    
print("Your age is:", age)
print("You were born in the year:", year)
print("Are you married?", is_married)
print("Are you true?", is_true)
print("Is the light on?", is_light_on)